server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: system
          project: ${PROJECT}
          environment: ${ENVIRONMENT}
          team: ${TEAM}
          host: ${HOSTNAME}
          host_class: ${HOST_CLASS}      # cloud-vm | vps
          __path__: /var/log/{syslog,messages,auth.log,kern.log,*.log}

  - job_name: journal
    journal:
      json: false
      max_age: 12h
      labels:
        job: journal
        project: ${PROJECT}
        environment: ${ENVIRONMENT}
        team: ${TEAM}
        host: ${HOSTNAME}
        host_class: ${HOST_CLASS}
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
