apiVersion: v1
kind: Namespace
metadata:
  name: obs-metrics
  labels:
    purpose: observability
    component: metrics
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs-logs
  labels:
    purpose: observability
    component: logs
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs-storage
  labels:
    purpose: observability
    component: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs-registry
  labels:
    purpose: observability
    component: registry
