apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.40.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/helm-values/loki.yaml
    - repoURL: https://github.com/simon-appwrk/monitoring-infrastructure
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: obs-logs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m
