apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.5.2
      helm:
        releaseName: grafana
        valueFiles:
          - $values/helm-values/grafana.yaml
    - repoURL: https://github.com/simon-appwrk/monitoring-infrastructure
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: obs-metrics

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m
