apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default

  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.16.1
      helm:
        releaseName: harbor
        valueFiles:
          - $values/helm-values/harbor.yaml
    - repoURL: https://github.com/simon-appwrk/monitoring-infrastructure
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: obs-registry

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 10m
